# -*- coding: utf-8 -*-
"""Fibonacci_Series.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ww0rtuMz_IxBSs9lJVGUP7SVjIAvUnDs
"""

n1=0
n2=1
print(n1)
print(n2)
for i in range(10):
    n3=n1+n2
    print(n3)
    n1=n2
    n2=n3