# -*- coding: utf-8 -*-
"""Hello_World!.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18TRS9X_JjWbgrbMYpbstzZsET1RibanD
"""

print('Hello World!')