# -*- coding: utf-8 -*-
"""positive_numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NepYIPUWQavJEOjtDvoMlXHu9KzX8Oqu
"""

list1=[12,-7,5,64,-14]
for number in list1:
  if number>0:
   print(number)

list2=[12,14,-95,3]
for number in list2:
  if number>0:
    print(number)