# -*- coding: utf-8 -*-
"""Text_Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l2LNti4gmAkoU4f9CMPzqfaJA9HUqlQZ
"""

# -------------------------------
# STEP 1: IMPORT LIBRARIES
# -------------------------------
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.utils import to_categorical
import random

# -------------------------------
# STEP 2: DEFINE TEXT
# -------------------------------
text = "hello world machine learning is fun"
text = text.lower()

# -------------------------------
# STEP 3: CHARACTER MAPPING
# -------------------------------
chars = sorted(list(set(text)))
char_to_num = {c:i for i,c in enumerate(chars)}
num_to_char = {i:c for i,c in enumerate(chars)}

n_chars = len(text)
n_vocab = len(chars)

# -------------------------------
# STEP 4: CREATE SEQUENCES
# -------------------------------
seq_length = 5
x_data = []
y_data = []

for i in range(0, n_chars - seq_length):
    in_seq = text[i:i+seq_length]
    out_seq = text[i+seq_length]
    x_data.append([char_to_num[c] for c in in_seq])
    y_data.append(char_to_num[out_seq])

n_patterns = len(x_data)
print("Total Patterns:", n_patterns)

# -------------------------------
# STEP 5: RESHAPE & NORMALIZE
# -------------------------------
X = np.reshape(x_data, (n_patterns, seq_length, 1))
X = X / float(n_vocab)
y = to_categorical(y_data)

# -------------------------------
# STEP 6: BUILD LSTM MODEL
# -------------------------------
model = Sequential()
model.add(LSTM(50, input_shape=(X.shape[1], X.shape[2])))
model.add(Dense(y.shape[1], activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam')

# -------------------------------
# STEP 7: TRAIN MODEL
# -------------------------------
model.fit(X, y, epochs=20, batch_size=1, verbose=2)

# -------------------------------
# STEP 8: GENERATE TEXT
# -------------------------------
# pick a random seed sequence
start = np.random.randint(0, len(x_data))
pattern = x_data[start]

print("\nSeed:")
print("".join([num_to_char[value] for value in pattern]))

generated_text = "".join([num_to_char[value] for value in pattern])

# generate 100 characters
for i in range(100):
    x = np.reshape(pattern, (1, len(pattern), 1))
    x = x / float(n_vocab)
    prediction = model.predict(x, verbose=0)

    # choose the most likely next character
    index = np.argmax(prediction)
    result = num_to_char[index]

    generated_text += result
    pattern.append(index)
    pattern = pattern[1:]

print("\nGenerated Text:")
print(generated_text)