# -*- coding: utf-8 -*-
"""Set_Operations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vSOjg0D7XRq3flWCC1DW3xH4oAkLRu1Y
"""

E = {0,2,4,6,8}
N = {1,2,3,4,5}
print("Union of E and N is", E|N);
print("Intersection of E and N is",E&N);
print("Difference of E and N is",E-N);
print("Symmetric of E and N is", E^N);