# -*- coding: utf-8 -*-
"""Image_Classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XJ9zo7Ig8tvgmR59X-daUZXpK0FfJb_p
"""

# Commented out IPython magic to ensure Python compatibility.
#importing dependencies
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.model_selection import train_test_split
# %matplotlib inline



import tensorflow as tf
import numpy as np

# Load the MNIST dataset from Keras
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

# Reshape x_train and x_test to 2D arrays
x_train_reshaped = x_train.reshape(x_train.shape[0], -1)
x_test_reshaped = x_test.reshape(x_test.shape[0], -1)

# Create DataFrames for training and testing data
df_train = pd.DataFrame(x_train_reshaped)
df_train['label'] = y_train

df_test = pd.DataFrame(x_test_reshaped)
df_test['label'] = y_test

# Concatenate train and test data to create a single DataFrame
data_mnist = pd.concat([df_train, df_test], ignore_index=True)

# Save the combined data to a CSV file named 'mnist_csv.csv'
data_mnist.to_csv('mnist_csv.csv', index=False)
print("MNIST dataset downloaded and saved as 'mnist_csv.csv'")

# Now load the newly created 'mnist_csv.csv' file
data = pd.read_csv('mnist_csv.csv')
print("Data loaded successfully from 'mnist_csv.csv'")
display(data.head())

#extracting daat from the dataset and viewing them up close
a = data.iloc[3,1:].values

#reshaping the extracted data into a reasonable size
a = a.reshape(28,28).astype('uint8')
plt.imshow(a)

#preparing the data
#separating labels and data values
df_x = data.iloc[:,1:]
df_y = data.iloc[:,0]

#creating test and train sizes/batches
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size = 0.2, random_state=4)

#check data
y_train.head()

#call rf classifier
rf = RandomForestClassifier(n_estimators=100)

#fit the model
rf.fit(x_train, y_train)

#prediction on the test data
pred = rf.predict(x_test)

pred

#check prediction accuracy
s = y_test.values

#calculate number of correctly predicted values
count = 0
for i in range(len(pred)):
  if pred[i] == s[i]:
    count = count + 1

count

#total values that the prediction code was run on
len(pred)

#accuracy value
14000/14000